trigger: none

parameters:
  - name: poolSelection
    displayName: 'Select the agent pool'
    type: string
    default: 'ubuntu-latest'
    values:
      - 'ubuntu-latest'
      - 'SH1'

  - name: suiteName
    displayName: 'Test Suite'
    type: string
    default: 'CICA_Suite_MulStates_FL.xml'
    values:
      - 'CICA_Suite_MulStates_FL.xml'
      - 'CICA_SuiteAll.xml'
      - 'MasterSuite_Excel.xml'
      - 'MasterSuite_NV_FL_Parallel_Retry.xml'
      - 'MasterSuite_NV_FL.xml'
      - 'MasterSuite_NV_Mul.xml'
      - 'MasterSuite_NV_MulLoginsParallel.xml'
      - 'MasterSuite_NV.xml'
      - 'MasterSuiteHealth.xml'
      - 'PolicyPaymentSuite.xml'
      - 'Signin-parallel-methods.xml'
      - 'States_Counties_Pall.xml'
      - 'Suite_ActivityReportsModule.xml'
      - 'Suite_CustomerModule.xml'
      - 'Suite_DashboardModule.xml'
      - 'Suite_GuaranteedIssue.xml'
      - 'Suite_NLife_PaymentsModule1.xml'
      - 'Suite_NV_2FLs.xml'
      - 'Suite_NV_MulStates_FL.xml'
      - 'Suite_PaymentsModule2.xml'
      - 'Suite_PolicyPaymentsModule.xml'
      - 'Suite_ProfileModule.xml'
      - 'Suite_RenewalPremiumReports.xml'
      - 'Suite_ReportModules.xml'
      - 'Suite_ReportModules2.xml'
      - 'Suite_Validation.xml'

jobs:
- job: RunOnUbuntu
  displayName: 'Run Tests on Ubuntu'
  condition: eq(variables['parameters.poolSelection'], 'ubuntu-latest')
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'Path'
        jdkDirectory: '/usr/lib/jvm/java-11-openjdk-amd64'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - script: |
        echo "Running Test Suite: $(suiteName)"
        ./run-tests.sh --suite $(suiteName)
      displayName: 'Run Selected Test Suite'

- job: RunOnWindows
  displayName: 'Run Tests on Windows'
  condition: eq(variables['parameters.poolSelection'], 'SH1')
  pool:
    name: SH1
  steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'Path'
        jdkDirectory: 'C:\Program Files\Java\jdk-20'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - script: |
        echo "Running Test Suite: $(suiteName)"
        ./run-tests.bat --suite $(suiteName)
      displayName: 'Run Selected Test Suite on Windows'
