pool:
  name: SH1

parameters:
  - name: SUITE_FILE
    displayName: 'Select the suite file to run'
    type: string
    default: 'Sanity_ApplicationModule.xml'
    values:
      - 'MasterSuite_Regression_Application_SingleLogin.xml'
      - 'MasterSuite_Sanity_GuaranteedIssue_MulLogins.xml'
      - 'MasterSuite_Sanity_GuaranteedIssue_QuadRun.xml'
      - 'MasterSuite_Sanity_GuaranteedIssue_SingleLogin.xml'
      - 'MasterSuite_Sanity_MulLogins.xml'
      - 'MasterSuite_Sanity_QuadRun.xml'
      - 'MasterSuite_Sanity_SingleLogin.xml'
      - 'Regression_AccountBalanceHistory.xml'
      - 'Regression_AccountBalanceReport.xml'
      - 'Regression_ActivityReports.xml'
      - 'Regression_AllModules.xml'
      - 'Regression_ApplicationModule.xml'
      - 'Regression_ApplicationPaymentStatusReport.xml'
      - 'Regression_CheckReport.xml'
      - 'Regression_CheckReportHistory.xml'
      - 'Regression_GuaranteedIssue.xml'
      - 'Regression_OtherModules.xml'
      - 'Regression_PaymentRefusedReport.xml'
      - 'Regression_RenewalPremiumReports.xml'
      - 'Regression_ReportModules.xml'
      - 'Regression_StandardToGuaranteed.xml'
      - 'Regression_StatusReport.xml'
      - 'Sanity_ApplicationModule.xml'
      - 'Sanity_GuaranteedIssue.xml'
      - 'Sanity_StandardToGuaranteed.xml'
      - 'Regression_DashboardModule.xml'
      - 'Regression_CustomerModule.xml'
      - 'Regression_PolicyPayment.xml'
      - 'Regression_ProfileModule.xml'

steps:
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'                              # Path to your pom.xml
      goals: 'clean test'                                  # Goals for Maven
      options: '-DsuiteXmlFile=src/test/resources/suites/citizens/${{ parameters.SUITE_FILE }}' # Parameterized suite file
      publishJUnitResults: true                            # Publish test results to Azure DevOps
      testResultsFiles: '**/target/surefire-reports/*.xml' # Path to the test results
      javaHomeOption: 'Path'
      jdkDirectory: 'C:\\Program Files\\Java\\jdk-20'      # JDK path on Windows server
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
