trigger:
- main  # This triggers the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

parameters:
- name: SUITE_FILE
  type: string
  default: 'MasterSuite_Regression_Application_SingleLogin.xml'  # Default suite file
  values:
    - MasterSuite_Regression_Application_SingleLogin.xml
    - MasterSuite_Sanity_GuaranteedIssue_MulLogins.xml
    - MasterSuite_Sanity_GuaranteedIssue_QuadRun.xml
    - MasterSuite_Sanity_GuaranteedIssue_SingleLogin.xml
    - MasterSuite_Sanity_MulLogins.xml
    - MasterSuite_Sanity_QuadRun.xml
    - MasterSuite_Sanity_SingleLogin.xml
    - Regression_AccountBalanceHistory.xml
    - Regression_AccountBalanceReport.xml
    - Regression_ActivityReports.xml
    - Regression_AllModules.xml
    - Regression_ApplicationModule.xml
    - Regression_ApplicationPaymentStatusReport.xml
    - Regression_CheckReport.xml
    - Regression_CheckReportHistory.xml
    - Regression_GuaranteedIssue.xml
    - Regression_OtherModules.xml
    - Regression_PaymentRefusedReport.xml
    - Regression_RenewalPremiumReports.xml
    - Regression_ReportModules.xml
    - Regression_StandardToGuaranteed.xml
    - Regression_StatusReport.xml
    - Sanity_ApplicationModule.xml
    - Sanity_GuaranteedIssue.xml
    - Sanity_StandardToGuaranteed.xml

stages:
- stage: Clean
  displayName: 'Clean Workspace'
  jobs:
  - job: CleanWorkspace
    displayName: 'Clean Workspace'
    steps:
    - script: |
        echo "Cleaning workspace..."
        rm -rf $(Build.SourcesDirectory)/*
      displayName: 'Clean Workspace'

- stage: Checkout
  displayName: 'Git Checkout'
  jobs:
  - job: GitCheckout
    displayName: 'Checkout Code from GitHub'
    steps:
    - script: |
        echo "Checking out branch: main"
        git clone -b main https://github.com/CodetruAutomation/CitizensAgentPortal_Automation.git $(Build.SourcesDirectory)
      displayName: 'Checkout Git Repository'

- stage: Test
  displayName: 'Run Tests'
  jobs:
  - job: MavenTest
    displayName: 'Maven Build and Test'
    steps:
    - task: JavaToolInstaller@0  # Install Java
      inputs:
        versionSpec: '17'  # Specify Java version
        jdkArchitectureOption: 'x64'  # Choose the architecture (x64 is common)

    - task: Maven@3
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/pom.xml'  # Path to your pom.xml
        goals: 'clean test'  # Maven goals to execute
        options: "-DsuiteXmlFile=src/test/resources/suites/citizens/$(SUITE_FILE)"  # Pass the suite file path
        publishJUnitResults: true  # Publish test results to Azure DevOps
        testResultsFiles: '**/target/surefire-reports/*.xml'  # Path to the test results

    - script: |
        echo "Running additional scripts or commands..."
        if [ -f ./your_script.sh ]; then
          chmod +x ./your_script.sh  # Make sure your script is executable
          ./your_script.sh  # Run the additional script
        else
          echo "your_script.sh not found!"  # Inform if the script doesn't exist
          exit 1  # Fail the job if the script is missing
        fi
      displayName: 'Run Additional Shell Script'
