# azure-pipelines.yml
trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

parameters:
  - name: SUITE_FILE
    type: string
    values:
      - MasterSuite_Regression_Application_SingleLogin.xml
      - MasterSuite_Sanity_GuaranteedIssue_MulLogins.xml
      - MasterSuite_Sanity_GuaranteedIssue_QuadRun.xml
      - MasterSuite_Sanity_GuaranteedIssue_SingleLogin.xml
      - MasterSuite_Sanity_MulLogins.xml
      - MasterSuite_Sanity_QuadRun.xml
      - MasterSuite_Sanity_SingleLogin.xml
      - Regression_AccountBalanceHistory.xml
      - Regression_AccountBalanceReport.xml
      - Regression_ActivityReports.xml
      - Regression_AllModules.xml
      - Regression_ApplicationModule.xml
      - Regression_ApplicationPaymentStatusReport.xml
      - Regression_CheckReport.xml
      - Regression_CheckReportHistory.xml
      - Regression_GuaranteedIssue.xml
      - Regression_OtherModules.xml
      - Regression_PaymentRefusedReport.xml
      - Regression_RenewalPremiumReports.xml
      - Regression_ReportModules.xml
      - Regression_StandardToGuaranteed.xml
      - Regression_StatusReport.xml
      - Sanity_ApplicationModule.xml
      - Sanity_GuaranteedIssue.xml
      - Sanity_StandardToGuaranteed.xml

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: CleanWorkspace
    jobs:
      - job: Clean
        steps:
          - task: DeleteFiles@1
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'

  - stage: Checkout
    jobs:
      - job: GitCheckout
        steps:
          - checkout: self
            clean: true

  - stage: Test
    jobs:
      - job: RunTests
        steps:
          - script: |
              mvn clean test -DsuiteXmlFile=src/test/resources/suites/citizens/$(SUITE_FILE)
            displayName: 'Run Test Suite'

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/testng-results.xml'
              testRunTitle: 'TestNG Results'
            displayName: 'Publish TestNG Results'
