trigger:
  branches:
    include:
      - main  # Adjust this to match your default branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

variables:
  SUITE_FILE: 'MasterSuite_Regression_Application_SingleLogin.xml'  # Default suite file; can be updated from Azure DevOps

stages:
- stage: CleanWorkspace
  displayName: 'Clean Workspace'
  jobs:
  - job: Clean
    displayName: 'Clean Workspace Directory'
    steps:
      - script: |
          echo "Cleaning workspace..."
          rm -rf $(Build.SourcesDirectory)/*
        displayName: 'Clean Workspace'

- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: MavenBuild
    displayName: 'Maven Build and Test'
    steps:
      - checkout: self  # Check out the source code
        displayName: 'Git Checkout'

      - task: JavaToolInstaller@0  # Install Java
        inputs:
          versionSpec: '17'  # Specify Java version
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
        displayName: 'Install Java 17'

      - task: MavenAuthenticate@0  # Optional: Authenticate if using private Maven repositories
        inputs:
          mavenAuthenticate: true
        displayName: 'Maven Authentication'

      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'  # Path to your pom.xml
          goals: 'clean test'  # Matching Jenkins goals with "test"
          options: '-DsuiteXmlFile=src/test/resources/suites/citizens/$(SUITE_FILE)'  # Set suite file
          publishJUnitResults: true  # Publish test results to Azure DevOps
          testResultsFiles: '**/target/surefire-reports/*.xml'  # Path to the test results
        displayName: 'Maven Build and Run Tests'

      - script: |
          echo "Publishing TestNG results..."
          # Example publishing TestNG results (customize if needed)
          # Replace with a task if Azure DevOps has specific handling for TestNG
        displayName: 'Publish TestNG Results'

      - script: |
          echo "Running additional scripts or commands..."
          chmod +x ./your_script.sh
          ./your_script.sh
        displayName: 'Run Additional Shell Script'
